### ISSUE TITLE
Dl-custom-content plugin causes error during upgrade

### ISSUE THREAD

**Issue by maartenschalekamp** [angusmcleod/discourse-layouts#6]
Unable to upgrade discourse when this plugin is enabled. First encountered this issue 2017-11-06 and still an issue.
Current discourse version: v1.9.0.beta4 +268

https://meta.discourse.org/t/dl-custom-content-plugin-causes-error-during-upgrade/73587

```I, [2018-01-10T18:19:19.587687 #15]  INFO -- : > cd /var/www/discourse && su discourse -c 'bundle exec rake db:migrate'
2018-01-10 18:19:27.333 UTC [798] discourse@discourse LOG:  duration: 106.000 ms  bind <unnamed>: SELECT COUNT(*) FROM (SELECT  1 FROM "users" LIMIT 20) subquery_for_count
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/var/www/discourse/plugins/dl-custom-content/plugin.rb:9:in `block (2 levels) in activate!'
/var/www/discourse/plugins/dl-custom-content/plugin.rb:8:in `class_eval'
/var/www/discourse/plugins/dl-custom-content/plugin.rb:8:in `block in activate!'
/var/www/discourse/lib/plugin/instance.rb:270:in `block in notify_after_initialize'
/var/www/discourse/lib/plugin/instance.rb:268:in `each'
/var/www/discourse/lib/plugin/instance.rb:268:in `notify_after_initialize'
/var/www/discourse/config/application.rb:219:in `each'
/var/www/discourse/config/application.rb:219:in `block in <class:Application>'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:49:in `each'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `public_send'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `method_missing'
/var/www/discourse/config/environment.rb:5:in `<top (required)>'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
I, [2018-01-10T18:19:28.152915 #15]  INFO -- : 
I, [2018-01-10T18:19:28.153330 #15]  INFO -- : Terminating async processes
161:signal-handler (1515608368) Received SIGTERM scheduling shutdown...```

**Comment by angusmcleod** [comment]
This is actually an issue with the widget (made by someone else) you're using, not this plugin.

https://github.com/jezdean/dl-custom-content

If you want to add arbitrary html in a widget, rather than use dl-custom-content, please try:

https://github.com/angusmcleod/layouts-custom-html

**Comment by maartenschalekamp** [comment]
Sorry, my mistake for posting it here and not at dl-custom-content.
Thanks!
